version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/openjdk:8
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1

jobs:
  test:
    <<: *docker_defaults
    steps:
      - checkout
      - restore_cache:
          key: circleci-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
            paths:
              - ~/.m2
            key: circleci-java-spring-{{ checksum "pom.xml" }}
      - run: mvn test

workflows:
  build-test:
    jobs:
      - test
