version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/openjdk:8
    - image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
      environment:
        discovery.type: single-node
        http.port: 9200
        transport.host: localhost
        network.host: 127.0.0.1

jobs:
  test-deploy:
    <<: *docker_defaults
    steps:
      - checkout
      - restore_cache:
          key: circleci-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
            paths:
              - ~/.m2
            key: circleci-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - add_ssh_keys:
          fingerprints:
            - "6f:6e:ed:68:b2:b1:67:70:24:b1:26:f5:9d:af:79:17"
      - deploy:
          command: ~/grid/.circleci/deploy.sh

workflows:
  build-test:
    jobs:
      - test-deploy
